Fix check for element in iframe vs normal scope
juggle/resize-observer pull request #123
Opened 2021-04-10 08:51 UTC by JayaKrishnaNamburu

Turns out in chrome the instance of elements are different in normal `window` vs elements inside `iframe`.

So, in this example https://codesandbox.io/s/wonderful-water-64s21 where all elements are inside portal. So, the scope of `obj` can be checked using `scope.Element`. But in this example https://codesandbox.io/s/observer-330-ucif1 the elements are created in global window but added to iframe dynamically. So, they both are not the same according to chrome.

Repo with the above check enabled --> https://github.com/JayaKrishnaNamburu/chrome-observer-bug

To compare with `Element` when `scope.Element` fails as fall back can solve the issue 😄
To extend check we can even do `obj.nodeType` because element nodes are `1`. But i am not sure about the observer scope, to which type of elements can one add a `ResizeObserver`.
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType#constants

2021-04-12 08:28 UTC, TremayneChrist requested changes

2021-04-12 08:28 UTC, TremayneChrist commented on src/utils/element.ts
> +   obj instanceof Element));
Check for instance of Element first, as this will cover 99% of use cases and then if it's false we can continue to get the window scope and try again. Tiny gains for the win :)

2021-04-12 10:20 UTC, JayaKrishnaNamburu commented on src/utils/element.ts
> +   obj instanceof Element));
Sure sure, sounds good too 👍

2021-04-12 13:31 UTC, TremayneChrist commented on src/utils/element.ts
> +   obj instanceof Element));
scope could be falsey with the latest changes and we could get an incorrect value. Was thinking that we could check if the the object is an instance of the Element before the scope event gets retrieved/set.

```js
if (object instanceof Element) {
   return true;
}
const scope = (obj as Element)?.ownerDocument?.defaultView;
...
```

2021-04-12 16:48 UTC, JayaKrishnaNamburu commented on src/utils/element.ts
> +   obj instanceof Element));
I think, i got it right this time 😄

2021-04-13 10:25 UTC, TremayneChrist commented on src/utils/element.ts
> +    return true
Semicolon

2021-04-13 10:27 UTC, TremayneChrist commented on src/utils/element.ts
> +    return true
Then we're good :)

2021-04-13 11:07 UTC, JayaKrishnaNamburu commented on src/utils/element.ts
> +    return true
Ahh , my prettier 😅

2021-04-15 08:44 UTC, TremayneChrist approved these changes

2021-04-15 08:46 UTC, merged